version: "2"
services:
  app:
    container_name: freachly
    image: sherifelkelesh/freachly
    restart: always
    build: .
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
